#include "diskScenes.h"

char EMPTY_FILE[0];
#define EMPTY_FILE_LEN 0

DD_ROOMS(ddRoomsTest, DD_ROOM(TEST_ROOM0_ZMAP, EMPTY_FILE));
DD_DUNGEONMAPS(dungeonMapTest, DD_DUNGEONMAP(DUNGEONMAPLEFTTEXTURE_BIN, DUNGEONMAPRIGHTTEXTURE_BIN));

DD_SCENES
(
    DD_SCENE(SCENE_MIDOS_HOUSE, ddRoomsTest, NULL, TEST_SCENE_ZSCENE, EMPTY_FILE, SDC_DEFAULT),
);

DD_CUTSCENES
(
    DD_CUTSCENE(SCENE_ZORAS_RIVER, CUTSCENEZORARIVER_BIN),
);

const s32 ddScenesCount = ARRAY_COUNT(ddScenes);
const s32 ddCutscenesCount = ARRAY_COUNT(ddCutscenes);